- src/main/java/eu/siacs/conversations/generator/IqGenerator.java
- src/main/java/eu/siacs/conversations/parser/IqParser.java
- src/main/java/eu/siacs/conversations/services/MessageArchiveService.java
- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
- src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java
- src/main/java/eu/siacs/conversations/xmpp/jingle/JingleConnection.java
- src/main/java/eu/siacs/conversations/xmpp/jingle/JingleConnectionManager.java
- src/main/java/eu/siacs/conversations/xmpp/jingle/JingleInbandTransport.java
- src/main/java/eu/siacs/conversations/xmpp/stanzas/AbstractStanza.java
- src/main/java/eu/siacs/conversations/xmpp/stanzas/IqPacket.java
I'm still unsure how I feel about this as a solution (readability wise it's pretty terrible). Thoughts / code review to make sure I'm not leaving any holes open appreciated.
Converting the type to an enum didn't end up being necessary... I wanted some guarantee that you wouldn't get an invalid packet type originally, but I can't remember why. Left it anyways because it prevents developers from assigning invalid packet types inadvertantly in future.
> Verify IQ responses

- .travis.yml
- build.gradle
- src/main/res/values-v21/themes.xml
- src/main/res/values/colors.xml
Adds some elements of the materials theme for v21 devices. This does not use `appcompat` as @iNPUTmice mentioned that he did not want to maintain a compatibility mode in the conference earlier. Instead, it is a separate theme that is only loaded on v21 devices. This also required updating the target SDK in the build script (otherwise the status bar isn't handled properly).
The status bar color is set to `colorPrimaryDark` as per the material guidelines:
I semi-arbitrarily picked an accent color from the Light blue [pallet](http://www.google.com/design/spec/style/color.html#color-color-palette) that can be found in the Google design giudelines. A700 `#ff0091ea`, but that can be changed easily if desired.
The action bar is also the correct color in the open apps menu (before it looked like …
> Add materials theme for v21 devices

- src/main/res/values-cs/strings.xml
Use ellipsis in CS strings (Android recommends using the correct Unicode characters; it looks much better on screen).
> s/.../…/ in CS strings

- build.gradle
Now that Transifex is being used, we shouldn't fail the build on extra translations since it will handle this for us the next time translations are generated / imported. Downgrade them to a warning as far as the linter is concerned.
> Don't fail on extra translations

- src/main/res/layout/activity_about.xml
This is a fix for a minor bug that didn't cause issues on Android 4 (except that the scroll bar was offset over the text a bit, but that was hardly noticable). However, on Android 5 the "pull down" animation is cut off on the edges.
Before:
After:
> Use margin instead of padding on about screen

- src/main/res/layout/activity_about.xml
The bottom spacing on the about page should still use padding instead of a margin, otherwise the scrollview cuts the last line of text off (sorry, didn't notice this in my last PR related to this issue).
> Fix bottom padding on about page

- src/main/java/eu/siacs/conversations/ui/ConversationActivity.java
- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
- src/main/java/eu/siacs/conversations/ui/XmppActivity.java
- src/main/res/values/strings.xml
- src/main/res/xml/preferences.xml
Adds a second input option to compliment the new "enter is send" option which allows the emoticons key to be replaced with an enter key (and makes sure the fragment gets reset when it's changed so that it actually shows up without requiring an app restart).
> Add option to swap enter/emoticon key

- src/main/java/eu/siacs/conversations/services/NotificationService.java
Adds two of the new notification features from API 21: Colored icon background and category (used for prioritizing messages, eg. users can specify that they don't want to be interrupted by anything but SMS/IM messages).
> Add some Android 21 notification features

- .gitignore
- src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java
- src/main/res/values-cs/strings.xml
- src/main/res/values-de/strings.xml
- src/main/res/values-es/strings.xml
- src/main/res/values-eu/strings.xml
- src/main/res/values-fr/strings.xml
- src/main/res/values-it/strings.xml
- src/main/res/values-nl/strings.xml
- src/main/res/values-sv/strings.xml
- src/main/res/values/strings.xml
- src/main/res/xml/preferences.xml
Removes legacy SSL support (and gitignores the navigation builder tool's temp files, which was apparently still in my .gitignore file when I committed).
> Remove legacy SSL support

- src/main/java/eu/siacs/conversations/services/NotificationService.java
Add the API 21 color/category options to the foreground notification as well.
> Add color / category to foreground notification

- build.gradle
- src/main/java/eu/siacs/conversations/crypto/OtrEngine.java
- src/main/java/eu/siacs/conversations/generator/MessageGenerator.java
- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
Hi,
you should update otr4j to version 0.22
see otr4j/otr4j#6 and jitsi/otr4j#20
otr4j supports in this version fragmentation so the api has changed slightly.
transformSending() returns now an array of strings.
> otr4j: update to 0.22

- src/main/java/eu/siacs/conversations/parser/MessageParser.java
Hi,
when the otr query messages have an additional message like conversations used
*"I would like to start a private (OTR encrypted) conversation but your client doesn’t seem to support that"* 
the the regex does not mach.
> MessageParser: fix the regex for otr query messages.

- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
Lower the priority of the "muted" snackbar below actual errors (eg. "nick is already taken") as we should probably not be required to unmute a conference to actually join it when things like this happen.
Fixes #939
> Show errors before mute snackbar

- src/main/res/values-cs/strings.xml
- src/main/res/values-de/strings.xml
- src/main/res/values-es/strings.xml
- src/main/res/values-nl/strings.xml
Remove a few unused strings (not super important; just doing some cleanup and figured that we might as well get rid of these — I thought Transifex would automatically, but I think there's been an import from it since this was removed, so I guess not).
> Removes some unused strings (the legacy SSL stuff)

- src/main/java/eu/siacs/conversations/xmpp/stanzas/MessagePacket.java
If the <body> tag is not first, their bot just silently drops the
stanza.  I know we shouldn't have to care about order, and I'm trying to
get them to fix it, but it's not high-priority for them since "most"
clients seem to work, so I'd like this workaround in.
> Vitelity's s.ms service requires <body> first

- src/main/java/eu/siacs/conversations/Config.java
- src/main/java/eu/siacs/conversations/utils/CryptoHelper.java
With #959 all ciphers of the platform were enabled, but this also
includes several suites that are considered as very weak, even down to
NULL- and anon-ciphers which disable completely disable encryption
and/or authentication. Especially the anon-ciphers could be easily used
for a mitm-attack.
To remove all weak ciphers a blacklist with patterns of cipher-names was
added to Config.java. The blacklist is based on the "mandatory discards"
that Mozilla suggests to not use for TLS-servers because they are weak
or known to be broken.
https://wiki.mozilla.org/Security/Server_Side_TLS#Mandatory_discards
> disable all really weak cipher suites

- src/main/java/eu/siacs/conversations/services/NotificationService.java
I've tried this debug version on different devices, and the led is really more like the Conversation green when set to full-green than with the Conversation's green...
Thanks !
> Green led color is better with "full-green"

- src/main/java/eu/siacs/conversations/ui/ChooseContactActivity.java
- src/main/java/eu/siacs/conversations/ui/XmppActivity.java
- src/main/res/menu/select_multiple.xml
- src/main/res/values/strings.xml
When passing the Choose Contact Activity a boolean called "multiple"
set to true, it now allows the user to select multiple contacts. Long
pressing a contact enters multiple selection mode and the selection is
confirmed using a button in the CAB. The Activity returns whether or not
multiple contacts were selected using the same boolean. If multiple
contacts were selected, an array of JID strings called "contacts" is
returned. The Choose Contact Activity now also honors "filter_contacts",
an array of strings containing JIDs that should not be displayed in
the picker.
The invite to conference dialog now uses this feature to enable inviting
multiple contacts at once. Additionally, Invite Contact uses
"filter_contacts" to only display contacts that are not yet
participating in the …
> Added multiple select to Choose Contact Activity (squashed)

- src/main/java/eu/siacs/conversations/ui/ManageAccountActivity.java
- src/main/java/eu/siacs/conversations/ui/adapter/AccountAdapter.java
- src/main/res/layout/account_row.xml
While I like the context-menu approach in general it can be somewhat tedious to enable/disable multiple but not all accounts. The added switch allows to toggle an account state from the ManageAccountActivity directly.
> Add toggle account-state switch

- src/main/java/eu/siacs/conversations/crypto/OtrEngine.java
- src/main/java/eu/siacs/conversations/generator/MessageGenerator.java
The current patch for https://github.com/siacs/Conversations/issues/1021 only sends out an error message on receival of unreadable messages from other OTR-Instances.
This patch tries to also inform the sender when the recipient already discarded session-keys the sender is still using.
I am still uncertain whether its a good idea to send a XMPP error-message but I attempted to stick to the approach you chose in https://github.com/siacs/Conversations/commit/99b2ef7e9d571dcfa386df4d0190ce626e657232
Please also see my comment in https://github.com/siacs/Conversations/issues/1021 in this regard.
> Fix OTR-Error messages (#1021)

- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
- src/main/java/eu/siacs/conversations/ui/SettingsActivity.java
- src/main/res/values-de/strings.xml
- src/main/res/values/strings.xml
- src/main/res/xml/preferences.xml
Attempt to fix #1084 by adding a new "Don't trust system CAs" preference under advanced options
that will change the behaviour of the MemorizingTrustManager. All formerly unknown certificates will raise a warning if checked. 
Please review and test carefully.
> Add option to use MTM without default TrustManager (#1084)

- src/main/java/eu/siacs/conversations/crypto/OtrEngine.java
- src/main/java/eu/siacs/conversations/generator/MessageGenerator.java
- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
- Fix session handling on contact status change: Do not reset
potentially active sessions; check peer's OTR-resource on disconnect
- use no-permanent-store hint instead of no-store to ensure
finished-messages are delivered to offline/disconnected clients
- add no-permanent-store to ask compliant servers not to archive
OTR messages
-
Further notes:
- If a contact is connected with several clients and disconnects with the OTR enabled client, that client will sometimes be listed in the resource dialog when I try to directly start a new OTR session. Haven't yet checked why and when this is the case, though.
- The Padlock symbol in the ActionBar is currently not updated on reception of an OTR finished message. Can we safely change line 375 in ConversationActivity from
`if …
> OTR: Fix onContactStatusChanged & dont archive OTR

- src/main/java/eu/siacs/conversations/ui/SettingsActivity.java
- src/main/res/values-de/strings.xml
- src/main/res/values/strings.xml
- src/main/res/xml/preferences.xml
Hi @iNPUTmice,
In my eyes it is a very bad practise to enable users to make trust decisions they can never revoke (leaving aside de-installation and wipe data). Therefore I'd like you to consider this PR, although I know you said that such an option would not be necessary.
> Add option to remove manually approved certificates

- README.md
The HTTPS server is throwing GitHub's certificate instead of a proper one, so I'm going to stick with HTTP for now.
> Fixed broken URL.

- src/main/res/values-v21/themes.xml
If you double click a message and enter the text selection contextual action bar, it's the default grey color. Instead, it should be the accent color.
I don't actually know what this is supposed to look like in 4.x devices, and since I don't have one to test with anyways (or fast enough internet to download an emulator here), I didn't change it for older devices.
> Change CAB to accent color in v21

- src/main/AndroidManifest.xml
- src/main/java/eu/siacs/conversations/ui/ConferenceDetailsActivity.java
- src/main/java/eu/siacs/conversations/ui/ContactDetailsActivity.java
- src/main/java/eu/siacs/conversations/ui/EditAccountActivity.java
- src/main/java/eu/siacs/conversations/ui/XmppActivity.java
- src/main/java/eu/siacs/conversations/utils/UIHelper.java
- src/main/res/layout/activity_contact_details.xml
- src/main/res/layout/activity_edit_account.xml
- src/main/res/layout/activity_muc_details.xml
Currently most activities get destroyed/recreated when rotating the device. This commit prevents this from happening where it is not necessary.
The most obvious improvements are:
* The options menu in the EditAccountActivity does not disappear when rotating the device.
* CSI inactive/active states are no longer sent on every rotate.
While I tested this and it works fine for me it would probably be good for others to test this first before merging.
> Handle some orientation changes manually

- src/main/java/eu/siacs/conversations/entities/Presences.java
Minor tweak to make the presences hash table final.
This is only partially my usual weirdness about things being final; we synchronize on the presences table a few times and it's unsafe to EVER sync on something that's not final (sync doesn't matter if the collection you're syncing on changes to a completely different collection in the middle of the operation).
> Don't synchronize on non-final field

- src/main/java/eu/siacs/conversations/crypto/PgpDecryptionService.java
- src/main/java/eu/siacs/conversations/crypto/PgpEngine.java
- src/main/java/eu/siacs/conversations/entities/Account.java
- src/main/java/eu/siacs/conversations/entities/Conversation.java
- src/main/java/eu/siacs/conversations/parser/MessageParser.java
- src/main/java/eu/siacs/conversations/services/NotificationService.java
- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
- src/main/java/eu/siacs/conversations/ui/ConversationActivity.java
- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/res/values/strings.xml
PGP messages are only decrypted while the correspondent conversation is in foreground. Because of that
- Notifications are not meaningful
- Depending on the device, it takes quite a while to decrypt everything, especially if PGP messages where sent from another device with carbon-copy enabled.
As messages are decrypted in order, it is also impossible to continue communicating while waiting for the decryption to finish.
This patch adds a decryption service to the backend, which keeps track of the (un)locked state of the Keychain and manages the decryption. Old messages are decrypted in-order; new ones as they come in.
> PGP messages background decryption

- build.gradle
- src/main/AndroidManifest.xml
- src/main/java/eu/siacs/conversations/persistance/FileBackend.java
- src/main/java/eu/siacs/conversations/ui/PublishProfilePictureActivity.java
- src/main/res/values/strings.xml
implements #1534 using the android-crop library
https://github.com/jdamcd/android-crop
This lets users crop their images instead of automatically cropping them.
> Let users crop their avatar images using the android-crop library

- src/main/java/eu/siacs/conversations/entities/Message.java
- src/main/java/eu/siacs/conversations/parser/PresenceParser.java
- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
- src/main/res/values/strings.xml
Currently when a contact requests your presence (but does not send you a message), you are not informed that they've added you. This makes it quite easy to miss presence requests. This PR fixes that by opening a conversation with the contact, and displaying their status (if available) as ~~if it were a chat state message~~ a normal message.
> Show status message when contact requests presence

- src/main/java/eu/siacs/conversations/entities/Account.java
- src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
As the status was removed for accounts with PGP enabled (c7a519498a88235488bb3a35d6220c64f7d88d0a), the signature has to be updated once.
> Regenerate PGP signatures once

- src/main/java/eu/siacs/conversations/entities/Message.java
The current implementation results in message duplication in some cases
> Correct uuid check according to RFC 4122

- src/main/java/eu/siacs/conversations/utils/DNSHelper.java
- src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java
This also enables the [SNI](https://tools.ietf.org/html/rfc6066#page-6) and [ALPN](https://tools.ietf.org/html/rfc7301) TLS extensions so xmpp can be hosted on the same port as other services.
Look at _xmpp-client._tcp.burtrum.org and _xmpp-client._tls.burtrum.org for examples, the way I have it set up _xmpp-client._tls. has a greater priority.
Let me know what needs done to get this merged, a gajim patch is in the works now as well...
I intend to write a XEP for this as well, but the short version is this:
Lookup _xmpp-client._tls. in addition to _xmpp-client._tcp, mix priorities and weights like they were the same SRV record.  For _tls records obviously connect over TLS, for _tcp nothing changes.
1. TLS certificates MUST be validated the same way as for STARTTLS. (ie, against the jid …
> Implement XEP-0368: SRV records for XMPP over TLS

- src/main/java/eu/siacs/conversations/entities/Message.java
- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
- src/main/java/eu/siacs/conversations/utils/UIHelper.java
- src/main/res/menu/message_context.xml
- src/main/res/values/strings.xml
In the rare case OpenKeychain returns an error (e.g. the private key is not imported) the problem might be fixed by the user, so there should be a possibility to retry decryption, because otherwise the message is "lost".
This PR adds an entry "retry decryption" to the message menu to provide said possibility.
(It also does not show gibberish as a message preview in case of a failed decryption anymore and makes the message preview for PGP messages consistent with the text shown in the message bubble.)
> PGP Retry decryption from message menu

- src/main/java/eu/siacs/conversations/utils/FileUtils.java
The path extracted from the Cursor might not be accessible for Conversations. FileUtils accesses URI information through the ContentProvider, so this wouldn't be noticed.
Fixes sharing from open-keychain's TemporaryContentProvider
> Check if path for URI is accessible

- src/main/java/eu/siacs/conversations/ui/ConversationActivity.java
Conversations supports switching chats using Alt/Ctrl+<1-9> on keyboards that have these keys. However, it doesn't differentiate between Right and Left Alt keys. Depending on the keyboard layout, Right Alt is already reserved for key combos used for entering special characters (e. g. Right Alt + 2 = ² on a German keyboard). In these cases, the user unintentionally switches the active chat when trying to enter a special character.
This PR changes the behavior by limiting key combos with Alt keys to Left Alt.
> Do not treat Right Alt key as a modifier for key combos

- src/main/java/eu/siacs/conversations/services/NotificationService.java
This fixes the issue where the first message in the notification was sent to pebble
(and possibly to other wear devices) for every update in the conversation, as
reported in #1249.
This is the same patch propoed in https://github.com/siacs/Conversations/issues/1249#issuecomment-245878335
> Use the last message in the content text instead of the first.

- src/main/java/eu/siacs/conversations/crypto/sasl/Anonymous.java
- src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java
I haven't tested the second commit that fixes bind to use the JID returned by the server because I don't have a machine with all the dependencies to build Conversations right now; the actual ANONYMOUS mechanism works fine though.
I'll try to get an Android dev environment setup and test the second commit too.
> SASL ANONYMOUS (no UI)

- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/java/eu/siacs/conversations/ui/widget/ClickableMovementMethod.java
According to https://github.com/siacs/Conversations/issues/1606 and https://github.com/siacs/Conversations/issues/1615, we can't have multiple clickable links and selectable text at once. I think this happens because `Linkify` applies `LinkMovementMethod` to `TextView` when `setTextIsSelectable(true)` applies `ArrowKeyMovementMethod`. They are incompatible with each other.
My solution: I apply my custom `ClickableMovementMethod` which extends `ArrowKeyMovementMethod` and allows to handle links like `LinkMovementMethod` does. Also I apply `Linkify.addLinks` to message spannable directly.
This works well on my device (6.0.1) and 4.1 and 5.1 emulators. Also it fixes https://github.com/siacs/Conversations/issues/1860 issue: it's not a ROM bug, I can reproduce it on my device and emulators.
> Text selection enhancement

- src/main/java/eu/siacs/conversations/services/NotificationService.java
- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
The dismissal is made through an additional extra to keep the changes in XmppConnectionService at a minimum and avoid duplicate code
What I don't particularly like about this solution:
- ~~having two separate actions in the pendingintent in NotificationService, but apparently it's needed (see: http://stackoverflow.com/questions/3127957/why-the-pendingintent-doesnt-send-back-my-custom-extras-setup-for-the-intent)~~ fixed as of 3c9de13
- ~~I didn't want to change conversation and the boolean to final, which would have been needed for the GPG encryption~~ fixed as of 3c9de13
> Dismiss the notification when replying from a wear notification [needs review!]

- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/java/eu/siacs/conversations/ui/widget/ListSelectionManager.java
- src/main/res/menu/message_context.xml
- src/main/res/values-ru/strings.xml
- src/main/res/values/strings.xml
In https://github.com/siacs/Conversations/issues/1615#issuecomment-167341953 user asked about selection option. I think now this option might be helpful when double tap is difficult, for example in case when message consists of only one link.
Unfortunately, Android API doesn't provide a method to start selection manually as you told in https://github.com/siacs/Conversations/issues/1615#issuecomment-167342778, but there is a workaround using Java reflection. I'm using this workaround in my project for 2 years and it behaves reliably. The "select text" menu item will be hidden if workaround doesn't work on a particular device.
> Add "Select text" context menu option

- src/main/java/eu/siacs/conversations/ui/EditMessage.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/java/eu/siacs/conversations/ui/widget/CopyTextView.java
- src/main/res/layout/message_received.xml
- src/main/res/layout/message_sent.xml
The modified EditMessage removes all spans on text paste. These spans may appear when you copy text with "parcelable" spans from one application to another (even from Conversations to Conversations).
The CopyTextView allows to transform text when user selects it and presses "copy". In this code it just removes all spans in transformTextForCopy callback (but in the future this behavior might be more complex). So when I copy text from Conversations and paste it, for example, in notes app, all "link" spans and "relative size" spans will be gone.
> Remove spans on copying or pasting a text

- src/main/java/eu/siacs/conversations/entities/Message.java
- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
`\n\u200B\n` is replaced with `\n\n` now.
In `getMergedBody` I apply custom `MergeSeparator` span to each `\n\n` separator, then in `MessageAdapter` I apply `RelativeSizeSpan` above each `MergeSeparator`.
It allows to get rid from extra `\u200B` character in text.
> Remove MERGE_SEPARATOR

- src/main/java/eu/siacs/conversations/Config.java
- src/main/java/eu/siacs/conversations/persistance/FileBackend.java
- src/main/java/eu/siacs/conversations/services/ExportLogsService.java
- src/main/java/eu/siacs/conversations/ui/ConversationActivity.java
- src/main/java/eu/siacs/conversations/ui/SettingsActivity.java
- src/main/java/eu/siacs/conversations/ui/SettingsFragment.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/res/values/strings.xml
- src/main/res/xml/file_paths.xml
- src/main/res/xml/preferences.xml
This commit sets a new checkbox that allows to keep files stored at the private storage of the application.
Received files are saved directly in the applications internal storage, inside files directory. The intents are properly set so the files can be shared and viewed directly from the internal storage.
The camera is also saving pictures directly in the applications internal storage, although in the cache directory. 
A couple of new preference rows were created to handle the internal storage disk space usage. One is for the cache, which opens Android's application settings so Cache can be cleaned. And the other one is to clean the files inside Files/ and Pictures/.
Regards,
Ignacio Quezada @ Tutus
> Support for private files

- src/main/java/eu/siacs/conversations/crypto/sasl/ScramMechanism.java
- src/main/java/eu/siacs/conversations/crypto/sasl/ScramSha256.java
- src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java
Refactor the SCRAM code a bit and add SCRAM-SHA-256 support.
Tested against [this prosody patch](https://bitbucket.org/SamWhited/prosody/commits/276fb8ca6c0f3d1d42e1fad12b7a9b70fa0251e6) and against the test vectors from [mellium.im/sasl](https://godoc.org/mellium.im/sasl).
> Add SCRAM-SHA-2 support

- docs/XEPs.md
Maybe style [XEP-0384: OMEMO Encryption](http://xmpp.org/extensions/xep-0384.html) would be better for user's convenience; of course for other XEP's as well
> Added XEP-0384

- src/main/java/eu/siacs/conversations/entities/Message.java
- src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
- src/main/java/eu/siacs/conversations/services/ExportLogsService.java
I believe the root cause is huge messages, but sometimes every column in a row throws an IllegalStateException, and the only alternative at that point is to ignore the message and move on.
When I queried my database, with the crashing UUID, some of the length(body) were 16364444 which is what leads me to think this is length related.  A better fix would be to allow crazy long messages, but at least this stops conversations from crashing to the point of being unusable forever.
> Stop Conversations force closing over sqlite errors due to long messages

- src/main/java/eu/siacs/conversations/ui/adapter/ConversationAdapter.java
- src/main/java/eu/siacs/conversations/ui/widget/UnreadCountCustomView.java
- src/main/res/layout/conversation_list_row.xml
- src/main/res/values-v21/themes.xml
- src/main/res/values/attrs.xml
- src/main/res/values/colors.xml
- src/main/res/values/themes.xml
This PR aims to add number of unread messages for each conversation as discussed on #2181 . Until now, the unread count is displayed as :
> Adds feature requested in #2181 : Unread count for each conversation

- src/main/java/eu/siacs/conversations/ui/adapter/ConversationAdapter.java
- src/main/res/layout/conversation_list_row.xml
The PR aims to add a sender label to each conversation in order to make the UX more effective. This is in reference to issue #2240
> Adds feature requested in #2240 : Adds sender label to last message of each conversation

- src/main/java/eu/siacs/conversations/services/NotificationService.java
- src/main/java/eu/siacs/conversations/ui/ContactDetailsActivity.java
- src/main/java/eu/siacs/conversations/ui/EditAccountActivity.java
- src/main/java/eu/siacs/conversations/ui/OmemoActivity.java
- src/main/java/eu/siacs/conversations/ui/XmppActivity.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/java/eu/siacs/conversations/ui/forms/FormFieldWrapper.java
This PR changes the deprecated `getResources.getColor()` method to `ContextCompat.getColor()`. A detailed explanation is given on [StackOverflow](http://stackoverflow.com/questions/31590714/getcolorint-id-deprecated-on-android-6-0-marshmallow-api-23).
> Changes deprecated getResources().getColor() method

- src/main/AndroidManifest.xml
- src/main/java/eu/siacs/conversations/services/NotificationService.java
- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
- src/main/res/xml/automotive_app_desc.xml
This patch adds required additions in order to show notifications
in Android Auto. Messages are read aloud and voice reply is
offered. The functionaliy has been tested with the Android Auto
standalone app as well as with the DHU simulator as described
here:
https://developer.android.com/training/auto/testing/index.html
Closes #2434
> Add Android Auto support to notifications

- src/main/java/eu/siacs/conversations/services/NotificationService.java
In the previous implementation for Android Auto, messages are only added
on Android N and above. In order to support older Android versions, the
messages need to be added always.
> Fix: Add messages to Notifications for Android Auto on Android M and older

- src/main/java/eu/siacs/conversations/services/NotificationService.java
- src/main/res/values/defaults.xml
- src/main/res/values/strings.xml
- src/main/res/xml/preferences.xml
I didn't like that I was only notified by a small icon in the notification bar when I'm using my phone while it's muted, so I think this feature, which is also available in other mobile messengers (and usually enabled by default), might be a good idea. 
Since it's disabled by default most users shouldn't notice the change unless they manually enable it.
> Added preference to control Heads-up Notifications (turned off by default)

- src/main/java/eu/siacs/conversations/crypto/PgpDecryptionService.java
- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
When receiving a PGP message which is not encrypted with YOUR key,
OpenKeychain shows a dialog, which tells you the private key to decrypt
the message is unavailable. However, Conversations won't give up
decrypting the message. So whether the subsequent messages are
decryptable or not, the decryption is blocked at the current message.
The commit fixes the bug in this way: Give up the current message when
the decryption intent is cancelled, so that subsequent messages can be
handled.
> Give up PGP decryption when intent is cancelled

- src/main/java/eu/siacs/conversations/services/NotificationService.java
Google messages now has this ( http://www.androidpolice.com/2017/08/03/android-messages-v2-3-update-adds-mark-read-button-notifications-now-available-apk-download/ )
We should too!
> NotificationService: add button to mark conversation as read

- src/main/res/values/strings.xml
Contact should be genitive (contact's), not plural (contacts)
> Fix typo in error_no_keys_to_trust_server_error

- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
Some clients show the room's name more prominent than the subject. I'd like to improve compatibilty/useability with such clients (e.g. converse.js). I sugest that Conversations also sets the room name identical to the room subject.
> setting room subject also sets room name

- src/main/res/layout/activity_edit_account.xml
The pull request solves Issue #2763. Pressing the soft keyboard next button now leads to the Password edit text.
> add soft keyboard next button functionality

- src/main/res/values-fr/strings.xml
It was translated to something like “add again”, which doesn’t carry the same meaning and can be confusing for users.
It would be useful to also check how it has been translated in other languages, and add a source comment for future translators.
This is related to #2778.
> Fix the French translation for the add_back string

- src/main/java/eu/siacs/conversations/ui/StartConversationActivity.java
- src/main/java/eu/siacs/conversations/utils/XmppUri.java
XEP-0147 defines URIs for roster actions with nime e.g. xmpp:romeo@montague.net?roster
This PR make Conversations use the name as the serverName
> allow roster action with name

- libs/MemorizingTrustManager/res/values-v21/themes.xml
- libs/MemorizingTrustManager/res/values/defaults.xml
- libs/MemorizingTrustManager/res/values/themes.xml
- libs/MemorizingTrustManager/src/de/duenndns/ssl/MemorizingActivity.java
Both, in dark theme and light theme, the Certificate dialogue was in light theme.
In dark theme:
In light theme:
> Fixes #2786 : Certificate dialogue not respecting dark theme solved

- src/main/java/eu/siacs/conversations/ui/StartConversationActivity.java
This is a very simple pull request which removes the deprecated method `MenuItemCompat.expandActionView(mMenuSearchView);`
> remove deprecated method

- src/main/java/eu/siacs/conversations/ui/BlocklistActivity.java
- src/main/java/eu/siacs/conversations/ui/ChooseContactActivity.java
- src/main/java/eu/siacs/conversations/ui/CreateConferenceDialog.java
- src/main/java/eu/siacs/conversations/ui/EnterJidDialog.java
- src/main/java/eu/siacs/conversations/ui/JoinConferenceDialog.java
- src/main/java/eu/siacs/conversations/ui/StartConversationActivity.java
- src/main/res/layout/create_conference_dialog.xml
- src/main/res/layout/enter_jid_dialog.xml
- src/main/res/layout/join_conference_dialog.xml
This pull request attempts to solve #2860. The create conference, join conference dialogs and enter jid dialogs are now retained across configuration change, by the use of dialog fragments.
> Retain dialog across configuration change

- src/main/java/eu/siacs/conversations/ui/EditAccountActivity.java
- src/main/java/eu/siacs/conversations/ui/UriHandlerActivity.java
This PR prevents WelcomeActivity from being invoked if MAGIC_CREATE_DOMAIN == null.
Supersedes https://github.com/siacs/Conversations/pull/2940
> WelcomeActivity must not be invoked if MAGIC_CREATE_DOMAIN == null

- src/main/res/layout/fragment_conversation.xml
This pull request aims to solve the bug of fab shadow in pre api 19 devices, introduced while adding scroll to bottom button.
> Solve fab shadow bug on pre api 19 devices

- src/main/java/eu/siacs/conversations/Config.java
- src/main/java/eu/siacs/conversations/ui/ConferenceDetailsActivity.java
As users can be banned from a chat room in Conversations but cannot be unbanned, it might be desirable to entirely turn off the ability to ban users.
This pull request allows to do that in Config.java.
> disable the ability to ban users from chat rooms in Config.java

- src/main/java/eu/siacs/conversations/ui/UriHandlerActivity.java
Currently QR scanner supports only URIs. VCard specification allows
embedding instant messaging protocols in the [`IMPP` field][0].
This change will extract the first XMPP URI from `IMPP` field if a VCard
has been scanned and process it just like if the XMPP URI was scanned
directly. In case the contact is not already present in the roster this
will pop up "Add contact" window.
Example VCard with this URI:
BEGIN:VCARD
FN:Test Contact
EMAIL:test@example.com
IMPP:xmpp:test@example.com
END:VCARD
[0]: https://tools.ietf.org/html/rfc6350#section-6.4.3
> Extend QR scanner to support VCard with IMPP field

- src/main/java/eu/siacs/conversations/services/NotificationService.java
Nicknames are case-sensitive.Perform case-sensitive matching for highlighting the own nickname in MUC messages and while checking whether to notify.
> Make nickname matching case-sensitive

- src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
This way we avoid repeating the code. Unlike `getWritableDatabase`, `onConfigure` is intended to be overridden.
In fact, `onConfigure` documentation specifically says: "Called when the database connection is being configured, to enable features such as write-ahead logging or *foreign key support*."
> move enabling of foreign key support to onConfigure

- src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
Conversations stores sensitive data, such as `SQLiteAxolotlStore` tables, in its database.
`secure_delete=ON` is the default for newer Android devices:
https://android-review.googlesource.com/c/platform/external/sqlite/+/209123
However, older devices had it disabled by default, so any database created than has this setting disabled and it will not be updated automatically.
Also, the default might be changed in the future (for example, to `FAST`, added in 2017), so it is safer to set it explicitly.
> explicitly set secure_delete pragma for SQLite database

- src/main/java/eu/siacs/conversations/parser/PresenceParser.java
- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
I recognized that Conversations will not broadcast idle in presence in case it is started and left in background. Reason is mLastActivity being zero.
Therefore other users using Conversations see the contact as being active when in fact it is inactive.
This PR tries to solve this by persisting the last active time stamp and then us this time as idleSince.
Furthermore I recognized that Conversations shows another contact as "currently online" even after it logged off from the xmpp server.
Reason is that Conversations receives a presence of type "unavailable" without any timestamp. In this case the contact stays "active".
I propose to simply check if the contact is entirely offline after a presence of type "unavailable" is received. If it is offline flag it as inactive.
> improve active_since implementation (XEP-0319: Last User Interaction in Presence)

- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/java/eu/siacs/conversations/utils/Patterns.java
The multiline flag is necessary to match a newline as `WORD_BOUNDARY`. Otherwise, a trailing slash is matched by it and is thus not included in the link.
A newline also seems to be added when multiple messages are merged into one bubble, leading to the behaviour described in #2887.
> Fixed trailing slashes in URLs followed by newline

- src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java
According to https://xmpp.org/extensions/xep-0045.html#registrar-discocat 'A Multi-User Chat service or room is identified by the "conference" category and the "text" type within Service Discovery.'.
I added this extra check because Conversations tried to use my ejabberd's push service "p2..." as muc service.
> improve identification of muc service

- src/main/res/values-v21/themes.xml
- src/main/res/values/themes.xml
This change sets the navigation bar color to secondary background color when using dark theme.
This avoids using default system color for navigation bar that could be white.
Before this change:
After this change:
>  Set navigation bar color to dark on dark theme 

- src/main/java/eu/siacs/conversations/entities/MucOptions.java
- src/main/java/eu/siacs/conversations/ui/ConferenceDetailsActivity.java
- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
- src/main/java/eu/siacs/conversations/ui/ConversationsActivity.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/java/eu/siacs/conversations/ui/util/MucDetailsContextMenuHelper.java
Up to now you can start a private conversation with a muc user by long-pressing on its avatar.
This PR tries to start a regular conversation instead, in case the user's true JID is known (i.e. the MUC is non-anonymous). Otherwise it is proceeded as before.
> WIP: start a new conversation by long press on avatar

- src/main/java/eu/siacs/conversations/services/NotificationService.java
...so no useless icon is shown on the status bar on Android 7 and older (as it was up to 2.2.9)
> Lower foreground service notification priority

- src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
Currently the user is shown a snackbar dialog in case he wants to enter a MUC that has been destroyed before. If the user selects "leave", the conversation will be archived but an existing bookmark will stay.
As the user can very easily recreate the MUC unintentionally by simply selecting the bookmark left I believe it would he desirable to simply remove the bookmark as well.
> remove bookmark after a room is destroyed

- src/main/res/values/defaults.xml
- src/quicksy/res/values/defaults.xml
Notifications from strangers are disabled by default in order to cope
with spam. On the other hand, this complicates contacting other users
for the first time, which leads to a bad user experience.
> Enable notifications from strangers by default

- src/main/java/eu/siacs/conversations/services/ExportBackupService.java
I've recently reset my phone after using the backup feature of Conversations, but while trying to restore my messages, I got a SQLite error in `logcat` (which I didn't copy unfortunately) saying something like "unexpected integer value for string column" and the backup failed. It referred to a line containing the arabic numbers `١٢٣٤٥٦٧٨٩٠` as a single message, but not surrounded by quotation marks as the other messages.
Fortunately, I was able to decrypt the file with my passwort on the computer, change the corresponding line and encrypt it again so that I was able to import the backup successfully.
Now, I've searched for the reason to this problem and found this line I've changed in the commit: [It seems the regular expression `\\d+` matches arabic numbers …
> Fix backup error for non-unicode numbers

- src/main/res/values-ro-rRO/strings.xml
I corrected a small, but annoying typo in the Romanian translation.
See https://dexonline.ro/definitie/tasta for the correct conjugation.
> Correct a small typo in Romanian translation

- src/main/res/values-v21/themes.xml
- src/main/res/values/themes.xml
This is consistent with the black background that is already used in
that activity.
Before:
After:
I've also reverted my previous commit that set the dark navigation bar for the rest of activities and made it use `tools:targetApi="21"` that is much cleaner than creating separate themes for API level 21.
> Use dark navigation bar in QR scanner activity

- src/main/java/eu/siacs/conversations/entities/Conversation.java
When using LMC I'd like Conversations to identify replaced messages based on the bare JID and not on the full JID. Otherwise a corrected message in a one-to-one-chat will be shown as a new message if the user's ressource changes in between. This for example happens in converse.js in case you log off and on in between sending the original and the corrected message.
Furthermore I believe that XEP-0308 states that the bare JID is supposed to be used for matching of a corrected message.
> LMC: find replacedMessages based on bare JID

- src/main/java/eu/siacs/conversations/ui/ShareLocationActivity.java
- src/main/res/layout/activity_share_location.xml
- src/main/res/values/colors.xml
- src/main/res/values/strings.xml
closes issue #3588 
When the blue and underlined OpenStreetMap is is clicked, the user is presented with this page in their web browser: [https://www.openstreetmap.org/copyright](https://www.openstreetmap.org/copyright)
This follows openstreetmap's guidelines as stated on that page.
Cheers!
> added openstreetmap copyright notice to maps

- src/main/java/eu/siacs/conversations/ui/ConferenceDetailsActivity.java
- src/main/res/layout/activity_muc_details.xml
- src/main/res/values/strings.xml
closes  #3447
I chose the string `participant(s)`, however I am unsure how this will affect the translatability of this string. If you have a better recommendation for this string, please let me know and I will change it.
> show number of participants in a MUC

- src/main/java/eu/siacs/conversations/ui/LocationActivity.java
- src/main/java/eu/siacs/conversations/ui/ShareLocationActivity.java
- src/main/res/layout/activity_share_location.xml
- src/main/res/values/colors.xml
- src/main/res/values/strings.xml
I believe the current implementation of OSM attribution is unnecessarily complex.
I propose to just use osmdroid's CopyrightOverlay because it's basically one line of code to be added and it gets the attribution text from the mapsource which is obviously the more flexible approach (e.g. if you want to support multiple map sources).
> simplify osm attribution

- README.md
I recently setup my own Prosody server, and tried to get Conversations with Push support working with it.
Unfortunately I wasted a bunch of time because even though I added the `cloud_notify` module to Prosody, and the module loaded without error, Conversations would show "XEP-0357: Push - Unavailable". This lead me to spend a bunch of time debugging the the `cloud_notify` module and XEP-0357 discovery, etc, etc..
It turns out the problem was that I didn't have **XEP-0198: Stream Management** support on my server, once I loaded that module everything worked as expected. Also, it makes perfect sense that stream management is required for Push to work efficiently.
This Pull Request just adds some information to the README.me file that mentions XEP-0198 support is required on the server. …
> Update README.md to mention XEP-0198 is required for push notifications

- src/main/res/values/defaults.xml
Most will need this anyway (or they can't control it on Oreo and later) or they can disable it, but I see F-Droid users with it off (since it's default) that disconnect all the time and don't get timely messages.
> Foreground service on by default

- src/main/java/eu/siacs/conversations/services/NotificationService.java
Set the incoming call notification category back to `CATEGORY_CALL`. This is what other apps like WhatsApp and Telegram are doing. Without a proper category 3rd-party apps are not able to notify a user about a call. For example, [Gadgetbridge](https://gadgetbridge.org/) currently doesn't start an incoming call notification/vibration on a smart watch during an incoming call in Conversations.
I don't know why the category was previously overridden as `CATEGORY_MESSAGE` in `modifyIncomingCall()`, so I'm not sure whether this breaks anything.
Tested with [Gadgetbridge](https://gadgetbridge.org/).
> Allow 3rd-party applications to know about an incoming call

- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
- src/main/java/eu/siacs/conversations/ui/widget/EditMessage.java
- src/main/res/values/strings.xml
Currently Conversations lacks any keyboard shortcut to send a message if enter_is_send is disabled.
KeyboardListener has been extended to include the original KeyEvent as an argument.
-------------------------
If passing the whole `KeyEvent` is too much, we can use `getMetaState()` and pass the bitflags of meta keys. Closes #3827.
> Support sending messages with ctrl+enter.

- src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
- src/main/java/eu/siacs/conversations/ui/ConversationsOverviewFragment.java
- In some places, we weren't nulling out references to destroyed objects. This
fixes that.
- (These were all discovered via LeakCanary instrumentation, and the fixes are
hopefully rather straightforward-looking.)
> Fix various memory leaks reported by LeakCanary

- src/main/java/eu/siacs/conversations/utils/FtsUtils.java
Conversations has been prepending an asterisk to every word in fulltext search.
On SQLite 3.8.6 and below that causes the query to never return anything.
Otherwise it is a symbol which is completely ignored.
> Fix search on API22 and below

- src/main/java/eu/siacs/conversations/parser/IqParser.java
Escaping the room jid at this point breaks channel join because escaping is done a second time later.
> fix escapeing in local channel discovery

- src/main/AndroidManifest.xml
- With large accounts (such as mine), Conversations starts hitting up against
the default heap limit pretty quickly, at which point it grinds to a halt as
GC pause times increase.
- Furthermore, it's impossible to complete a backup with such an account, since
Conversations will just run out of memory before the backup can complete.
- Enabling the `android:largeHeap` flag asks the OS for a bit more memory, which
hopefully alleviates the problem for larger accounts.
> Enable the android:largeHeap flag

- src/main/java/eu/siacs/conversations/xmpp/jingle/stanzas/IceUdpTransportInfo.java
This attribute is mandatory as per the XEP.
'network' is too, but this requirement will be relaxed once https://github.com/xsf/xeps/pull/1014 gets merged.
> Add 'id' attribute to outgoing ICE-UDP candidates

- src/main/java/eu/siacs/conversations/utils/UIHelper.java
When processing `/me` messages which are both sent to and received from MUC's, Conversations will render the message using the user's alias name within that MUC chat, so participants can choose the name displayed in their messages in the MUC. For example, if my alias within a MUC is `molly`, then sending the message "/me is using conversations.im" to that MUC will locally be rendered as "*molly* is using conversations.im".
In a direct chat with another user, incoming `/me` messages are rendered using the remote user's contact name, if set. For example, if I receive the message "/me is using dino.im" from another user `jane@example.com`, who is in my roster as "Jane Doe", then the message will locally be rendered as "*Jane Doe* is using dino.im". However, when *sending* `/me` messages in a …
> Use account display name in /me command in one-to-one chats

- src/main/java/eu/siacs/conversations/xmpp/jingle/SessionDescription.java
This is a feature of WebRTC that's [not standardized][1] and only supported by libwebrtc. Since there's no support in jingle for passing this capability from one peer to another, we're currently hard-coding this option into both the local candidate and also the remote candidate so they can use it.
But I'm trying to call a user that isn't using WebRTC, and renomination is causing the call to stay in "connecting..." state for 10 or 20 seconds, sometimes longer, while both sides wait for the other to nominate something based on their individual beliefs about the standards they're using.
Removing this seems to make connecting relatively instantaneous.
If we want to reintroduce this feature, we should probably make a XEP so the peers can negotiate honestly about it, and only use it if both …
> Remove Renomination from WebRTC Options

- src/main/res/menu/message_context.xml
Two ideas:
* muscle memory - there's a lot more quoting in general than message correction so fingers want to touch the last entry
* UX design - actions used more often on top, here Correction is higher since it's used more often for self messages than Quote
> Always show Quote as last action

- src/main/java/eu/siacs/conversations/Config.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
- src/main/java/eu/siacs/conversations/ui/util/QuoteHelper.java
- src/main/java/eu/siacs/conversations/ui/widget/EditMessage.java
- src/main/java/eu/siacs/conversations/utils/MessageUtils.java
- src/main/java/eu/siacs/conversations/utils/UIHelper.java
Answering feature request #3981 for nested quotations in compliance with XEP-0393. It basically loops over the body as long as it finds QuoteStarts and reapplies the QuoteSpan. On quoting quotes, it deletes any quotes that are nested too deeply. Also, on quoting quotes that contain French quotes, it replaces those French quotes with XEP-0393 quotes.
<a href="https://user-images.githubusercontent.com/32270710/130408656-6520b809-84af-457d-b750-4bbfa8491f51.png"><img src="https://user-images.githubusercontent.com/32270710/130408656-6520b809-84af-457d-b750-4bbfa8491f51.png" width="200" /></a>
Nesting depth is limited by Config.QUOTE_MAX_DEPTH (currently 7), to limit it based on dev experience w.r.t. performance and aesthetics. Depth of quoting nested quotes is limited by …
> Feature: nested quotes

- src/main/java/eu/siacs/conversations/ui/AboutActivity.java
- src/main/java/eu/siacs/conversations/ui/ConversationActivity.java
- src/main/java/eu/siacs/conversations/ui/LocationActivity.java
- src/main/java/eu/siacs/conversations/ui/MemorizingActivity.java
- src/main/java/eu/siacs/conversations/ui/RecordingActivity.java
- src/main/java/eu/siacs/conversations/ui/ScanActivity.java
- src/main/java/eu/siacs/conversations/ui/SettingsActivity.java
- src/main/java/eu/siacs/conversations/ui/XmppActivity.java
- src/main/java/eu/siacs/conversations/ui/util/SettingsUtils.java
- src/main/res/values/defaults.xml
- src/main/res/values/strings.xml
- src/main/res/xml/preferences.xml
This PR adds a new setting to conversations to prevent taking screenshots of the app and to hide the content in the app switcher (similar to Threema, Signal and most banking apps).
The new checkbox was added to the **Privacy** section of the settings. By default, the option is currently switched off.
New checkbox in settings screen  | How the app is displayed in the app switcher if turned on
:-------------------------:|:-------------------------:
> Prevent taking screenshots if desired

- src/conversations/java/eu/siacs/conversations/ui/ImportBackupActivity.java
This PR is a follow up of #4133 to cover the `ImportBackupActivity`. 
The only activity not covered now by screenshot prevention should be the `ChooseCountryActivity` of Quicksy. 
I have left that one out because there is no way to activate screenshot prevention before reaching this screen.
> Fix import backup activity not covered by screenshot prevention

- src/main/java/eu/siacs/conversations/ui/util/QuoteHelper.java
- src/main/java/eu/siacs/conversations/utils/UIHelper.java
#4148 destroyed the possibility to send messages starting with or consisting only of the ">.<" emoticon. This PR fixes this bug.
Thanks to my tech talk friends for reporting and testing. :)
> Bugfix: >.<

- src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
#4170 revealed that with SQLite fluke, unlikely but possible, can occur when an FTS4 vtable is dropped without automatic clean-up of its additional tables, leaving the database in an inconsistent state even when the transaction where this happened ultimately failed.
> Make sure messages_index is always cleaned up completely

- src/main/java/eu/siacs/conversations/entities/MucOptions.java
- src/main/java/eu/siacs/conversations/parser/PresenceParser.java
This is used when something goes wrong with a MUC, e.g. a connection error made the MUC kick you out. In this case you generally want to try to rejoin. Showing a toast with an option to do so seems like a sensible first step.
I recently made a Prosody [plugin](https://modules.prosody.im/mod_ping_muc.html) that tries to check if you are still connected after s2s connections to a MUC have been lost, communicating to clients if the answer is negative. Telling the user that they were kicked isn't really accurate in this case and the more accurate status code `333` was not supported yet, so here goes.
Currently reusing the same `conference_unknown_error` string since it is close enough and I couldn't think of a good and compact message explaining it better.
> Add handling of status code 333

- src/main/java/eu/siacs/conversations/entities/Conversation.java
At some point a refactor changed this check from checking that the quicksy
domain itself is talking to you, to checking that anyone using quicksy is
talking to you, which breaks the notifications from strangers setting for
quicksy users.
> A Quicky user can be a stranger

- src/main/java/eu/siacs/conversations/ui/ConversationsActivity.java
- src/main/java/eu/siacs/conversations/ui/EditAccountActivity.java
...as OEMs kill [1] the app and ignore Push messages and never wake up the app.
My experience _(and for others in the support group)_ goes like this:
* recommend Quicksy/Snikket/Conversations for Play users
* they install, we make contact
* everything works for a day
* the second day they appear offline
* no matter 1:1/group messages are not acknowledged
* I send an SMS
* they open the app, get the messages
* next day they go offline again
* stay offline for the next 4 days
If I'm able to meet with them, I can:
* ask for their device
* explain the issue _($hitty OEMs, whitelists for big money corps, etc)_
* while trying to confusingly navigate Android settings
* set autostart to manual
* put the app on the ignore battery optimizations list
If I'm not able to meet them? Nothing, no fix, …
> Always ask to disable battery optimisations

- README.md
- docs/user/backup.md
- docs/user/migrating_to_new_device.md
- src/main/java/eu/siacs/conversations/ui/util/EditMessageActionModeCallback.java
Recently – but not for the first time – I had the need for a step-by-step tutorial on how to migrate from one device to another. I don't like to link to the Readme.md, because it's very long, has many topics, and even if I send them a link to an anchor, I fear people might get lost. I like it even less to link to some 3rdparty page that's not regularly updated and so on. Long story short, I'd like to have a docs directory in the source code with simple markdown files that contain step-by-step tutorials. And I'd make a beginning with the migration tutorial.
It would also be worth considering i18n for these documents in the future.
> Migration tutorial

- README.md
Two of the recommended plugins got merged in 1.4, and don’t exist any longer, and when using flatpak the plugins must be installed that way.
> Update recommendations for Gajim

- src/main/java/eu/siacs/conversations/ui/SearchActivity.java
- src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
Just like a MUC, search results lack the context to be sure who sent a message, so show the name in the result item.
> Show the name of the sender in search results
