src/main/java/eu/siacs/conversations/services/NotificationService.java

This implements basic notifications to the Pebble through the app (using
an intent).  This simply hooks into NotificationService.notify().
This is pretty basic, but it works (I haven't tested to see how the
intent is received when the Pebble app is not around, though). More
fancy stuff could probably be added to avoid getting flooded, but the
Pebble app already does a good job a filtering notification (e.g.,
screen on or quiet times).
Squashed version of #649.
Signed-off-by: Olivier Mehani <shtrom@ssji.net>

Send notification to Pebble on new message

---

docs/XEPs.md
src/main/java/eu/siacs/conversations/entities/Message.java
src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
src/main/java/eu/siacs/conversations/ui/adapter/ConversationAdapter.java
src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java

Prevents messages that start with `/me\ ` from being merged and replaces the command with the nickname of the person who sent the message.
Fixes #865

Add XEP-0245 (/me command) support

---

src/main/java/eu/siacs/conversations/services/NotificationService.java

Ensure type safety in Pebble notifications
Also use forward-compatible screen-on detection
(I also tweaked the syntax a bit in the Pebble notification construction; this wasn't strictly necessary, but it makes it a lot easier to read IMO)

Type safety and deprecated API forward-compatibility fixes for Notifications

---

src/main/java/eu/siacs/conversations/services/NotificationService.java
src/main/java/eu/siacs/conversations/utils/UIHelper.java
src/main/res/values-de/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-eu/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-nl/strings.xml
src/main/res/values/strings.xml

Correct the download file string on notifications

---

src/main/java/eu/siacs/conversations/utils/UIHelper.java
src/main/res/values/strings.xml

Fix string substitutions with unknown filetypes

---

src/main/java/eu/siacs/conversations/utils/UIHelper.java
src/main/res/values/strings.xml

Added new file type names for file transfers

---

src/main/java/eu/siacs/conversations/ui/XmppActivity.java
src/main/java/eu/siacs/conversations/ui/adapter/AccountAdapter.java

To be able to change primary color I propose to change the color of the online-text in the account activity to green instead of primary color.

Changed online color to green instead of primary

---

src/main/res/values-cs/strings.xml

Czech translation

---

src/main/java/eu/siacs/conversations/entities/Message.java
src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
src/main/java/eu/siacs/conversations/utils/UIHelper.java

and add an constant for the "/me " string.

fix mergable() for /me command.

---

src/main/java/eu/siacs/conversations/parser/MessageParser.java
src/main/java/eu/siacs/conversations/ui/ConversationFragment.java

should also fixed #877 
maybe it's a good idea to change the otr state when the other does. I am not really sure.

otr: switch to the otr-state the partner alternate.

---

settings.gradle
src/main/AndroidManifest.xml
src/main/res/values-cs/strings.xml
src/main/res/values-de/strings.xml
src/main/res/values-es/strings.xml
src/main/res/values-eu/strings.xml
src/main/res/values-fr/strings.xml
src/main/res/values-it/strings.xml
src/main/res/values-iw/strings.xml
src/main/res/values-nl/strings.xml
src/main/res/values-ru/strings.xml
src/main/res/values-sv/strings.xml
src/main/res/values-zh-rCN/strings.xml
src/main/res/values-zh-rTW/strings.xml
src/main/res/values/strings.xml

Remove :libs:minidns too from settings.gradle

Remove title_activity_conversations and use app_name instead

---

docs/XEPs.md

added XEP-0085: Chat State Notifications

added XEP-0085: Chat State Notifications to docs

---

src/main/java/eu/siacs/conversations/services/NotificationService.java

A little change to the LED color code. 
Making this will allow the led to work correctly on xperia devices !

Some changes to the LED color in notifications !

---

src/main/java/eu/siacs/conversations/persistance/FileBackend.java

When publishing the metadata for an avatar that was cached, Conversations currently specifies an image size of zero (`bytes='0'`).  This happens because `avatar.size` [isn't][1] [set][2] for cached avatars.  Not sure about the best place to do that (e.g., just setting `avatar.size = file.length()` in [`isAvatarCached()`][3] would work as well).  Either way, this commit should at least show the issue.  (Note that most of the diff is just indentation change.)
[1]: https://github.com/siacs/Conversations/blob/4aab45533ac8a32be2fe66b266b845aed02acf1b/src/main/java/eu/siacs/conversations/persistance/FileBackend.java#L322
[2]: https://github.com/siacs/Conversations/blob/4aab45533ac8a32be2fe66b266b845aed02acf1b/src/main/java/eu/siacs/conversations/persistance/FileBackend.java#L337
[3]: …

Set file size also for cached avatars

---

src/main/java/eu/siacs/conversations/generator/MessageGenerator.java
src/main/java/eu/siacs/conversations/parser/AbstractParser.java
src/main/java/eu/siacs/conversations/parser/MessageParser.java
src/main/java/eu/siacs/conversations/services/XmppConnectionService.java

Please consider as follow-up on https://github.com/siacs/Conversations/pull/1035 and double-check the changes.
Thanks!

add delivery receipts for private muc msgs & enable update last-seen for muc-msgs

---

build.gradle
src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
src/main/java/eu/siacs/conversations/ui/ConversationActivity.java
src/main/res/layout-w960dp/fragment_conversations_overview.xml
src/main/res/layout/conversation_list_row.xml
src/main/res/layout/fragment_conversations_overview.xml
src/main/res/values-de/strings.xml
src/main/res/values-v21/dimens.xml
src/main/res/values/strings.xml

I liked your idea to end a conversation by swiping it out and figured that its rather simple to implement when making use of another 3rd party library: https://github.com/timroes/EnhancedListView
What do you think about this approach?

Enable end-conversation by swipe gesture

---

.travis.yml
build.gradle

make use of the archivesBaseName and
rename only 'zipaligned' release build.

update android sdk and support library.

---

src/main/AndroidManifest.xml
src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
src/main/java/eu/siacs/conversations/services/ExportLogsService.java
src/main/java/eu/siacs/conversations/ui/ExportLogsPreference.java
src/main/res/values/strings.xml
src/main/res/xml/preferences.xml

For description and discussion see #1295

Preference to backup logs to SD card

---

README.md

Update build system in README

---

src/main/java/eu/siacs/conversations/generator/IqGenerator.java
src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
src/main/java/eu/siacs/conversations/ui/EditAccountActivity.java
src/main/java/eu/siacs/conversations/ui/XmppActivity.java
src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java
src/main/res/values/strings.xml

* Fixes issue #308 
* Captcha request / submit compatible with pidgin captcha handling. 
* Displays the captcha scaled to the current text scaling factor (it is assumed the image has text to display, so it is likely to require the same scaling)
Since I've only tested with limited resources, I'd welcome further testing before merging.

Implemented account registration with captcha

---

src/main/java/eu/siacs/conversations/services/AvatarService.java

For conferences with only one other occupant, their avatar is shown as the conference tile. This makes it hard to distinguish conferences from one-to-one chats just by looking at the tile. It is especially a problem when an one-to-one chat with the same contact occupying the conference is also in the list .
This commit tries to improve this by putting the own avatar next to the contacts' one in the conference tile. An argument against this would be, that obviously one is part of every conversation one is in. However, the following point of view makes it look more plausible: Conference tiles represent a room of people where everyone can talk with everyone and you are just one of them.

Show own avatar in tile for conferences with only one other occupant next to theirs

---

art/conversations_baloon.svg

Logo clean-up

---

src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java

Fixes https://github.com/siacs/Conversations/issues/1648

use batch transactions when writing roster

---

build.gradle
src/main/java/eu/siacs/conversations/ui/ConversationActivity.java

https://github.com/siacs/Conversations/issues/1567 and upgrades openpgp-api to v10.

Fixes having to choose PGP twice, upgrades openpgp-api to 10

---

src/main/java/eu/siacs/conversations/entities/Contact.java
src/main/java/eu/siacs/conversations/entities/Presence.java
src/main/java/eu/siacs/conversations/entities/Presences.java
src/main/java/eu/siacs/conversations/entities/ServiceDiscoveryResult.java
src/main/java/eu/siacs/conversations/generator/PresenceGenerator.java
src/main/java/eu/siacs/conversations/parser/PresenceParser.java
src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
src/main/java/eu/siacs/conversations/ui/StartConversationActivity.java
src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java

Only for items that give presence with caps.  Cached by caps in sqlite, and always fetched from there if there's a match.
Closes #1643

Service Discovery for roster items

---

src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java

Shows XMPP URI as links, other than Web URL's and Email Addresses. Also performs respective actions on clicking XMPP URI.

Fix Issue #1634 : Shows XMPP URI as links.

---

src/main/java/eu/siacs/conversations/crypto/axolotl/SQLiteAxolotlStore.java

Was probably just a copy/paste typo.

Renaming of variable

---

CHANGELOG.md
README.md
src/main/java/eu/siacs/conversations/crypto/axolotl/AxolotlService.java
src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
src/main/java/eu/siacs/conversations/xmpp/XmppConnection.java
src/main/java/eu/siacs/conversations/xmpp/jingle/JingleConnection.java

fixes some spelling-errors, as found by 
https://github.com/ka7/misspell_fixer
Affecting just documentation and logcat, should not break any already translated text or code.

spelling fixes

---

src/main/java/eu/siacs/conversations/crypto/axolotl/XmppAxolotlMessage.java

The line overwrites this.innerkey with the value that was already there.

Remove copy of innerkey

---

src/main/java/eu/siacs/conversations/ui/adapter/MessageAdapter.java
src/main/java/eu/siacs/conversations/utils/GeoHelper.java

Add geo: link support in longer messages

---

src/main/res/layout/create_conference_dialog.xml

Updated to the text color attribute so it fits to the bright and dark theme appropriately.

Update create_conference_dialog.xml to also match dark theme.

---

README.md

I have just updated the link to the OpenPGP website.

Fix OpenPGP link

---

build.gradle
src/main/java/eu/siacs/conversations/persistance/FileBackend.java
src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
src/main/java/eu/siacs/conversations/ui/ConversationActivity.java
src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
src/main/java/eu/siacs/conversations/ui/EditMessage.java
src/main/java/eu/siacs/conversations/utils/MimeUtils.java

From talk in #2217 , this is a PR to disallow compression of GIFs
and to add support for GBoard's GIFs.

Do not compress GIFs, allow GBoard to send GIFs

---

.travis.yml
libs/MemorizingTrustManager/build.gradle

Travis is breaking, here is a possible fix.

Updated travis and Trust Manager to fix build

---

src/main/java/eu/siacs/conversations/ui/BlocklistActivity.java
src/main/java/eu/siacs/conversations/ui/EditAccountActivity.java
src/main/res/menu/choose_contact.xml
src/main/res/values/strings.xml

Added an option to directly add a jid to block list from BlocklistActivity

fixes #2336 : added an option to directly add a jid to block list

---

src/main/java/eu/siacs/conversations/services/NotificationService.java

Fix for issue https://github.com/siacs/Conversations/issues/2342
Adds the message senders in MUC notifications
Before:
After:

Modifies notification for MUC conversations

---

src/main/java/eu/siacs/conversations/ui/ConversationFragment.java
src/main/res/layout/fragment_conversation.xml
src/main/res/values/strings.xml

This can be used by screen readers and other accessibility aids.

Add content description to send button

---

README.md

Take a look at [my branch for how it would look](https://github.com/uchchishta/Conversations/tree/patch-1)
[Also I found you can have more badges from bountysource](http://blog.bountysource.com/post/87257081709/bountysource-badges) but need a trackerID I didn't find.
*****
*Edit*: found the tracker_id for per project, but still no team_id for open bounties.
`https://api.bountysource.com/badge/team?team_id=MISSING&amp;style=bounties_posted`

add badges in README.md & align center

---

src/main/java/eu/siacs/conversations/entities/DownloadableFile.java
src/main/java/eu/siacs/conversations/entities/Message.java
src/main/java/eu/siacs/conversations/http/AesGcmURLStreamHandler.java
src/main/java/eu/siacs/conversations/http/HttpDownloadConnection.java
src/main/java/eu/siacs/conversations/http/HttpUploadConnection.java

Read support for 12-byte IVs in addition to 16-byte IVs

---

.github/ISSUE_TEMPLATE.md

And make example version as current

Add field for actual result in issue template

---

src/main/java/eu/siacs/conversations/ui/adapter/ConversationAdapter.java
src/main/res/layout/conversation_list_row.xml

Show an Icon in the Conversations List if last Message was a Location/Voice/File

---

src/main/java/eu/siacs/conversations/services/MemorizingTrustManager.java
src/main/java/eu/siacs/conversations/ui/UriHandlerActivity.java

New pull request with only one commit instead of [this](https://github.com/siacs/Conversations/pull/2809).

AppCompat Migration contribution

---

src/main/AndroidManifest.xml

For details see https://developer.android.com/reference/android/R.attr.html#appCategory
> Apps which are primarily social apps, such as messaging, communication, email, or social network apps.

Classify in the "social" app category

---

src/main/java/eu/siacs/conversations/ui/service/CameraManager.java

If the orientations of `textureView` and `cameraResolution` didn't match, `frame` got distorted to a long, narrow rectangle in the calculation of `framePreview` that then got used in `buildLuminanceSource` to crop the preview image before processing. As a result, QR codes were only recognized when they were much smaller than the red square drawn on the screen.
This commit fixes this by doing the calculation with the correct orientation in the situation described above.
I tested the code with a smartphone and a tablet and the codes were recognized as soon as the were fully inside the displayed square.
Additionally, the displayed hint points are now drawn at the correct positions, which previously was not the case.
This probably also fixes the problems described in #2866.

Improved QR code recognition when screen and camera orientation don't match

---

src/main/java/eu/siacs/conversations/ui/UriHandlerActivity.java

Also check for XMPP URI validity if there are no configured accounts
and the WelcomeActivity is active.

UriHandlerActivity: Always check for XMPP URI validity

---

README.md
src/main/res/values/about.xml

Fixed small typos on README and about.xml

Fixed small typos

---

src/main/res/values/about.xml

Since RecyclerView it's used now

EnhancedListView deleted from about.xml

---

src/main/AndroidManifest.xml

...so I don't end up with two apps named "Conversations" in KISS launcher
Ref: https://github.com/Neamar/KISS/issues/932#issuecomment-377022353

Keep app name as Legacy in activity

---

build.gradle

Legacy - Bump versionCode too

---

src/main/java/eu/siacs/conversations/ui/SettingsActivity.java

I believe, the paths have changed.

fix cleanPrivateStorage()

---

src/main/java/eu/siacs/conversations/utils/GeoHelper.java

- only match valid float numbers
- match uri with parameter
You can try it out on https://regex101.com/r/eOCQLW/1. My changes are untested, because I got a null pointer exception during build (even before my change).
https://tools.ietf.org/html/rfc5870#section-3.3

fix geo uri regex (fix #3050)

---

src/main/java/eu/siacs/conversations/utils/Patterns.java
src/main/java/eu/siacs/conversations/utils/XmppUri.java

I don't pretend to understand fully the last part of the regex, but from preliminary REPL tests it should work.
Didn't test live as I can't build from this machine.

Patterns: attempt at fixing complex XMPP URIs

---

.travis.yml

A maybe fix - just one obviously bug

fix travis-build after adding build flavor for quicksy

---

README.md

User in MUC was not sure if deactivate meant "disconnect" or "delete"... he chose wrong.

This is sadly needed

---

src/main/java/eu/siacs/conversations/services/XmppConnectionService.java
src/main/java/eu/siacs/conversations/ui/ConferenceDetailsActivity.java
src/main/res/menu/muc_details.xml
src/main/res/values/strings.xml

This implements the ability to destroy a group chat.

implement room destruction

---

CHANGELOG.md

Fixed a little typo in Changelog.md

Fixed typo in Changelog.md

---

fastlane/metadata/android/en-US/changelogs/362.txt

Please retag 2.6.4 after merging so it's included ;)

Add changelog for 362

---

src/main/res/values-fr/strings.xml

I corrected a typo in the french version.

corrected typo

---

src/main/java/eu/siacs/conversations/ui/RtpSessionActivity.java

Fix screen blinking during the call for some Samsung phones

---

src/main/java/eu/siacs/conversations/ui/ConferenceDetailsActivity.java

Tried around a little to fix #4139 and this works for me. Is it a good solution? I wouldn't know, please tell me what you think. :)

Fixing xmpp:uri bug in channel details. #4139

---

src/main/java/eu/siacs/conversations/utils/Patterns.java

Bugfixes w.r.t. URLs

---

README.md

Add instructions on how to build WebRTC.

Clarify build instructions.

---

src/main/java/eu/siacs/conversations/ui/util/ShareUtil.java

Prevents copying something different from what was linked, such as in the
message "fine.gif https://example.com"

Use the same mechanism for link copying and linkification
